### ISSUE TITLE
CIRI: test_remove_neighbors sometimes fails on CI server. 

### ISSUE THREAD

**Issue by oopsmonk** [iotaledger/entangled#1397] opened 2019-08-08 15:57 UTC
**Describe the bug**
`//ciri/api/tests:test_remove_neighbors` sometimes fails on CI server, it will pass after a retry. 
https://buildkite.com/iota-foundation/entangled-prs/builds/1932#f6804f37-9ff8-401a-8719-1a7a487be0bb/70-1886

**Expected behavior**
The result of the test case should be stable.

**Comment by thibault-martinez** [comment] 2019-08-08 16:02
Duplicate of #1352

**Closed as completed by thibault-martinez** 2019-08-08 16:02 UTC
Labels: C-bug, P-high, A-ciri, S-duplicate

**Comment by oopsmonk** [comment] 2019-08-08 16:05
hah...thanks
