### ISSUE TITLE
ciri: Exit when config file is not given

### ISSUE THREAD

**Issue by Citrullin** [iotaledger/entangled#769] opened 2019-02-02 00:17 UTC
**Precondition:**
Cross-compilation of ciri for armv7 or arm64.

ARM64
```
bazel build --crosstool_top=@iota_toolchains//tools/aarch64--glibc--bleeding-edge-2018.07-1:toolchain --cpu=aarch64 --host_crosstool_top=@bazel_tools//tools/cpp:toolchain //ciri
```

ARMv7
```
 bazel build --crosstool_top=@iota_toolchains//tools/armv7-eabihf--glibc--bleeding-edge-2018.07-1:toolchain --cpu='armeabi-v7a' --compiler='gcc' --host_crosstool_top=@bazel_tools//tools/cpp:toolchain //ciri
```

**Expected behavior:**
When executing ciri, it should run out of the box when all configuration parameters are given. Even if the configuration file is not given.

**Actual behavior:**
```bash
./ciri \
--snapshot-file="external/snapshot_mainnet/file/downloaded" \
--snapshot-signature-file="external/snapshot_sig_mainnet/file/downloaded" \
--snapshot-signature-index=10 \
--snapshot-signature-depth=6 \
--snapshot-signature-pubkey="TTXJUGKTNPOOEXSTQVVACENJOQUROXYKDRCVK9LHUXILCLABLGJTIPNF9REWHOIMEUKWQLUOKD9CZUYAC" \
--num-keys-in-milestone=20 \
--db-path="db/mainnet.db"
2019-02-02 00:10:01: consensus_conf:    ERR: Snapshot configuration file not found
```

**Comment by th0br0** [comment] 2019-02-02 01:06
See https://github.com/iotaledger/entangled/blob/develop/consensus/conf.bzl for where the files are currently expected to be.

**Comment by thibault-martinez** [comment] 2019-02-04 14:47
I just talked with Philipp and the issue is that there is no CLI option to specify the snapshot configuration file (the one coming from the snapshot repository).
So running cIRI without bazel is currently not possible.

There is an easy fix for this: to make this file not mandatory.
- If it's found, we are probably running through bazel and all snapshot variables are correctly set
- If it's not found, we have to specify all snapshot variables with their CLI option respectively

I'll do a PR to fix this.

**Comment by francescolavra** [comment] 2019-02-05 11:03
Actually it is possible to run cIRI without bazel, but you have to take care that the snapshot config files are at the correct path (external/snapshot*) relative to the working directory. Also, cIRI needs its own configuration file to be found at ciri/conf.yml (again, relative to the working directory).

**Comment by thibault-martinez** [comment] 2019-02-05 11:18
Hi @francescolavra,
You are right, I agree that it's technically possible, but IMHO the snapshot configuration file shouldn't be mandatory as it is just a convenience file filling some variables that can be set with CLI options.

**Comment by Citrullin** [comment] 2019-02-05 12:40
@francescolavra That is the way I currently do it on my Orange Pis. Works fine, I am able to execute it. But there are some usability issues there. I need to rename ciri into app, so that I can create the directory ciri and put everything into it. Additionally, since you can configure everything via command line arguments, it should not throw an exception when everything needed is given via command line arguments. You could also add a check if the command line arguments or the config file is given. Returning some message like: "Please configure ciri via command line arguments or the configuration file."

**Closed as completed** 2019-03-26 13:26 UTC
Labels: E-low, C-bug, P-low, A-ciri
